#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me

# Define variables for old and new strings
str_to_replace="server_name _;"
new_string="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

# Update the package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a default Nginx index page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Use sed to replace the server block in the Nginx configuration
sudo sed -i -e "s|$str_to_replace|$new_string|" /etc/nginx/sites-enabled/default

# Start Nginx
sudo service nginx start
