#!/usr/bin/env bash
# configuring 301 redirect
sudo apt-get update
sudo apt-get install -y nginx

# Create a default Nginx configuration that listens on port 80
echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/html/;
    index index.htm index.html index.nginx-debian.html;

    location / {
        try_files $uri $uri/ =404;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx (without using systemctl)
sudo /etc/init.d/nginx restart

# Check if Nginx is running
if pgrep nginx > /dev/null; then
    echo "Nginx has been installed and configured successfully."
else
    echo "Nginx installation or configuration failed."
fi
