#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me and have a custom 404 page

# Define variables for old and new strings
str_to_replace_server="server_name _;"
new_server_block="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=bbVZo4Yw7pI;\n\t}"

# New variables for custom 404 page
str_to_find_404="# pass PHP scripts to FastCGI server"
new_404_config="error_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t\treturn 404 \"Ceci n\'est pas une page\n\";\n\t}\n\n\t# pass PHP scri>

# Update the package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a default Nginx index page
echo "Hello World!" > /var/www/html/index.html

# Use sed to replace the server block in the Nginx configuration
sudo sed -i -e "s|$str_to_replace_server|$new_server_block|" /etc/nginx/sites-enabled/default

# Use sed to add the custom 404 page configuration
sudo sed -i "s|$str_to_find_404|$new_404_config|" /etc/nginx/sites-enabled/default

# Create the custom 404 page
echo "Ceci n\'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Restart Nginx
sudo service nginx restart
