#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me and create a custom 404 page

# Define variables for old and new strings
str_to_replace="server_name _;"
new_string="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=bbVZo4Yw7pI;\n\t}"

# Update the package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a default Nginx index page
echo "Hello World!" > /var/www/html/index.html

# Use sed to replace the server block in the Nginx configuration
sudo sed -i -e "s|$str_to_replace|$new_string|" /etc/nginx/sites-enabled/default

# Create a custom 404 error page with the required message
echo -e "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Add a custom error page configuration to Nginx
sudo sed -i 's|server_name _;|server_name _;\n\n\tlocation /xyzfoo {\n\t\talias /var/www/html/404.html;\n\t}|' /etc/nginx/sites-enabled/default
# Get the hostname of the server
server_hostname=$(hostname)

org_string="location / {"
new_string="location / {\n\t\tadd_header X-Served-By $server_hostname;\n"

# Create a custom Nginx configuration using sed
sudo sed -i "s|$org_string|$new_string|" /etc/nginx/sites-enabled/default
# Restart Nginx
sudo service nginx restart
