#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

# Check if all 4 parameters are provided
if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Disable strict host key checking
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
