#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
killer()
{
	rm -r /var/run/myscript.pid
	exit
}
touch /var/run/myscript.pid
echo "$$" > /var/run/myscript.pid
while ((1 > 0)); do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" && killer' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'killer' SIGQUIT
done
