#!/usr/bin/env bash
# Bash script that displays content of the current directory In a list format

list=$(ls)

for f in $list; do
	if [ -f "$f" ] && [[ "$f" != .* ]] && [[ "$f" == *-* ]]; then
		echo "${f#*-}"
	fi
done
